# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import AsyncOperationResult
from ._models import CertificateListDescription
from ._models import CertificateProperties
from ._models import CertificateResponse
from ._models import DeviceRegistryNamespaceDescription
from ._models import ErrorAdditionalInfo
from ._models import ErrorDetail
from ._models import ErrorDetails
from ._models import ErrorMessage
from ._models import ErrorResponse
from ._models import GroupIdInformation
from ._models import GroupIdInformationProperties
from ._models import IotDpsPropertiesDescription
from ._models import IotDpsSkuDefinition
from ._models import IotDpsSkuInfo
from ._models import IotHubDefinitionDescription
from ._models import IpFilterRule
from ._models import ManagedServiceIdentity
from ._models import NameAvailabilityInfo
from ._models import Operation
from ._models import OperationDisplay
from ._models import OperationInputs
from ._models import PrivateEndpoint
from ._models import PrivateEndpointConnection
from ._models import PrivateEndpointConnectionProperties
from ._models import PrivateLinkResources
from ._models import PrivateLinkServiceConnectionState
from ._models import ProvisioningServiceDescription
from ._models import ProxyResource
from ._models import Resource
from ._models import SharedAccessSignatureAuthorizationRuleAccessRightsDescription
from ._models import SystemData
from ._models import TagsResource
from ._models import TrackedResource
from ._models import UserAssignedIdentity
from ._models import VerificationCodeRequest
from ._models import VerificationCodeResponse
from ._models import VerificationCodeResponseProperties

from ._enums import AccessRightsDescription
from ._enums import AllocationPolicy
from ._enums import CertificatePurpose
from ._enums import CreatedByType
from ._enums import DeviceRegistryNamespaceAuthenticationType
from ._enums import IotDpsSku
from ._enums import IpFilterActionType
from ._enums import IpFilterTargetType
from ._enums import ManagedServiceIdentityType
from ._enums import NameUnavailabilityReason
from ._enums import PrivateLinkServiceConnectionStatus
from ._enums import PublicNetworkAccess
from ._enums import State
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AsyncOperationResult",
    "CertificateListDescription",
    "CertificateProperties",
    "CertificateResponse",
    "DeviceRegistryNamespaceDescription",
    "ErrorAdditionalInfo",
    "ErrorDetail",
    "ErrorDetails",
    "ErrorMessage",
    "ErrorResponse",
    "GroupIdInformation",
    "GroupIdInformationProperties",
    "IotDpsPropertiesDescription",
    "IotDpsSkuDefinition",
    "IotDpsSkuInfo",
    "IotHubDefinitionDescription",
    "IpFilterRule",
    "ManagedServiceIdentity",
    "NameAvailabilityInfo",
    "Operation",
    "OperationDisplay",
    "OperationInputs",
    "PrivateEndpoint",
    "PrivateEndpointConnection",
    "PrivateEndpointConnectionProperties",
    "PrivateLinkResources",
    "PrivateLinkServiceConnectionState",
    "ProvisioningServiceDescription",
    "ProxyResource",
    "Resource",
    "SharedAccessSignatureAuthorizationRuleAccessRightsDescription",
    "SystemData",
    "TagsResource",
    "TrackedResource",
    "UserAssignedIdentity",
    "VerificationCodeRequest",
    "VerificationCodeResponse",
    "VerificationCodeResponseProperties",
    "AccessRightsDescription",
    "AllocationPolicy",
    "CertificatePurpose",
    "CreatedByType",
    "DeviceRegistryNamespaceAuthenticationType",
    "IotDpsSku",
    "IpFilterActionType",
    "IpFilterTargetType",
    "ManagedServiceIdentityType",
    "NameUnavailabilityReason",
    "PrivateLinkServiceConnectionStatus",
    "PublicNetworkAccess",
    "State",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
