# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any
from typing_extensions import Self

from azure.core import PipelineClient
from azure.core.credentials import AzureKeyCredential
from azure.core.pipeline import policies
from azure.core.rest import HttpRequest, HttpResponse

from ._configuration import IotHubGatewayServiceAPIsConfiguration
from ._serialization import Deserializer, Serializer
from .operations import (
    BulkRegistryOperations,
    CloudToDeviceMessagesOperations,
    ConfigurationOperations,
    DevicesOperations,
    DigitalTwinOperations,
    JobsOperations,
    ModulesOperations,
    QueryOperations,
    ServiceOperations,
    StatisticsOperations,
)


class IotHubGatewayServiceAPIs:  # pylint: disable=too-many-instance-attributes
    """IotHubGatewayServiceAPIs.

    :ivar configuration: ConfigurationOperations operations
    :vartype configuration: azext_iot.sdk.iothub.service.operations.ConfigurationOperations
    :ivar statistics: StatisticsOperations operations
    :vartype statistics: azext_iot.sdk.iothub.service.operations.StatisticsOperations
    :ivar devices: DevicesOperations operations
    :vartype devices: azext_iot.sdk.iothub.service.operations.DevicesOperations
    :ivar bulk_registry: BulkRegistryOperations operations
    :vartype bulk_registry: azext_iot.sdk.iothub.service.operations.BulkRegistryOperations
    :ivar query: QueryOperations operations
    :vartype query: azext_iot.sdk.iothub.service.operations.QueryOperations
    :ivar jobs: JobsOperations operations
    :vartype jobs: azext_iot.sdk.iothub.service.operations.JobsOperations
    :ivar cloud_to_device_messages: CloudToDeviceMessagesOperations operations
    :vartype cloud_to_device_messages:
     azext_iot.sdk.iothub.service.operations.CloudToDeviceMessagesOperations
    :ivar service: ServiceOperations operations
    :vartype service: azext_iot.sdk.iothub.service.operations.ServiceOperations
    :ivar modules: ModulesOperations operations
    :vartype modules: azext_iot.sdk.iothub.service.operations.ModulesOperations
    :ivar digital_twin: DigitalTwinOperations operations
    :vartype digital_twin: azext_iot.sdk.iothub.service.operations.DigitalTwinOperations
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials.AzureKeyCredential
    :keyword endpoint: Service URL. Default value is
     "https://fully-qualified-iothubname.azure-devices.net".
    :paramtype endpoint: str
    :keyword api_version: Api Version. Default value is "2026-11-01-preview". Note that overriding
     this default value may result in unsupported behavior.
    :paramtype api_version: str
    """

    def __init__(
        self,
        credential: AzureKeyCredential,
        *,
        endpoint: str = "https://fully-qualified-iothubname.azure-devices.net",
        **kwargs: Any
    ) -> None:
        self._config = IotHubGatewayServiceAPIsConfiguration(credential=credential, **kwargs)
        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
                policies.DistributedTracingPolicy(**kwargs),
                policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
                self._config.http_logging_policy,
            ]
        self._client: PipelineClient = PipelineClient(base_url=endpoint, policies=_policies, **kwargs)

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False
        self.configuration = ConfigurationOperations(self._client, self._config, self._serialize, self._deserialize)
        self.statistics = StatisticsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.devices = DevicesOperations(self._client, self._config, self._serialize, self._deserialize)
        self.bulk_registry = BulkRegistryOperations(self._client, self._config, self._serialize, self._deserialize)
        self.query = QueryOperations(self._client, self._config, self._serialize, self._deserialize)
        self.jobs = JobsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.cloud_to_device_messages = CloudToDeviceMessagesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.service = ServiceOperations(self._client, self._config, self._serialize, self._deserialize)
        self.modules = ModulesOperations(self._client, self._config, self._serialize, self._deserialize)
        self.digital_twin = DigitalTwinOperations(self._client, self._config, self._serialize, self._deserialize)

    def send_request(self, request: HttpRequest, *, stream: bool = False, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client.send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, stream=stream, **kwargs)  # type: ignore

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> Self:
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details: Any) -> None:
        self._client.__exit__(*exc_details)
