# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .event_route_py3 import EventRoute
    from .model_data_py3 import ModelData
    from .incoming_relationship_py3 import IncomingRelationship
    from .query_specification_py3 import QuerySpecification
    from .query_result_py3 import QueryResult
    from .inner_error_py3 import InnerError
    from .error_py3 import Error
    from .error_response_py3 import ErrorResponse, ErrorResponseException
    from .digital_twin_models_list_options_py3 import DigitalTwinModelsListOptions
    from .event_routes_list_options_py3 import EventRoutesListOptions
except (SyntaxError, ImportError):
    from .event_route import EventRoute
    from .model_data import ModelData
    from .incoming_relationship import IncomingRelationship
    from .query_specification import QuerySpecification
    from .query_result import QueryResult
    from .inner_error import InnerError
    from .error import Error
    from .error_response import ErrorResponse, ErrorResponseException
    from .digital_twin_models_list_options import DigitalTwinModelsListOptions
    from .event_routes_list_options import EventRoutesListOptions
from .model_data_paged import ModelDataPaged
from .object_paged import ObjectPaged
from .incoming_relationship_paged import IncomingRelationshipPaged
from .event_route_paged import EventRoutePaged

__all__ = [
    'EventRoute',
    'ModelData',
    'IncomingRelationship',
    'QuerySpecification',
    'QueryResult',
    'InnerError',
    'Error',
    'ErrorResponse', 'ErrorResponseException',
    'DigitalTwinModelsListOptions',
    'EventRoutesListOptions',
    'ModelDataPaged',
    'ObjectPaged',
    'IncomingRelationshipPaged',
    'EventRoutePaged',
]
