# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Configuration(Model):
    """Configuration.

    :param id:
    :type id: str
    :param schema_version:
    :type schema_version: str
    :param labels:
    :type labels: dict
    :param content:
    :type content: :class:`ConfigurationContent
     <iothubclient.models.ConfigurationContent>`
    :param content_type:
    :type content_type: str
    :param target_condition:
    :type target_condition: str
    :param created_time_utc:
    :type created_time_utc: datetime
    :param last_updated_time_utc:
    :type last_updated_time_utc: datetime
    :param priority:
    :type priority: int
    :param statistics:
    :type statistics: dict
    :param etag:
    :type etag: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'schema_version': {'key': 'schemaVersion', 'type': 'str'},
        'labels': {'key': 'labels', 'type': '{str}'},
        'content': {'key': 'content', 'type': '{object}'},
        'content_type': {'key': 'contentType', 'type': 'str'},
        'target_condition': {'key': 'targetCondition', 'type': 'str'},
        'created_time_utc': {'key': 'createdTimeUtc', 'type': 'iso-8601'},
        'last_updated_time_utc': {'key': 'lastUpdatedTimeUtc', 'type': 'iso-8601'},
        'priority': {'key': 'priority', 'type': 'int'},
        'statistics': {'key': 'statistics', 'type': '{long}'},
        'etag': {'key': 'etag', 'type': 'str'},
    }

    def __init__(self, id=None, schema_version=None, labels=None, content=None, content_type=None, target_condition=None, created_time_utc=None, last_updated_time_utc=None, priority=None, statistics=None, etag=None):
        self.id = id
        self.schema_version = schema_version
        self.labels = labels
        self.content = content
        self.content_type = content_type
        self.target_condition = target_condition
        self.created_time_utc = created_time_utc
        self.last_updated_time_utc = last_updated_time_utc
        self.priority = priority
        self.statistics = statistics
        self.etag = etag
