# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Metadata(Model):
    """Metadata.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param last_updated_utc:
    :type last_updated_utc: :class:`VariantValueDateTime
     <iothubclient.models.VariantValueDateTime>`
    :param last_updated_version:
    :type last_updated_version: long
    :param last_updated_configuration:
    :type last_updated_configuration: str
    :param last_updated_configuration_digest:
    :type last_updated_configuration_digest: str
    :ivar has_children:
    :vartype has_children: bool
    :ivar nested:
    :vartype nested: dict
    """

    _validation = {
        'has_children': {'readonly': True},
        'nested': {'readonly': True},
    }

    _attribute_map = {
        'last_updated_utc': {'key': 'LastUpdatedUtc', 'type': 'VariantValueDateTime'},
        'last_updated_version': {'key': 'LastUpdatedVersion', 'type': 'long'},
        'last_updated_configuration': {'key': 'LastUpdatedConfiguration', 'type': 'str'},
        'last_updated_configuration_digest': {'key': 'LastUpdatedConfigurationDigest', 'type': 'str'},
        'has_children': {'key': 'HasChildren', 'type': 'bool'},
        'nested': {'key': 'Nested', 'type': '{Metadata}'},
    }

    def __init__(self, last_updated_utc=None, last_updated_version=None, last_updated_configuration=None, last_updated_configuration_digest=None):
        self.last_updated_utc = last_updated_utc
        self.last_updated_version = last_updated_version
        self.last_updated_configuration = last_updated_configuration
        self.last_updated_configuration_digest = last_updated_configuration_digest
        self.has_children = None
        self.nested = None
