# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class X509CertificateMetadata(Model):
    """X509CertificateMetadata.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar subject_name: Distinguished name from the certificate.
    :vartype subject_name: str
    :ivar sha1_thumbprint: SHA-1 hash value of the certificate as a
     hexadecimal string.
    :vartype sha1_thumbprint: str
    :ivar sha256_thumbprint: SHA-256 hash value of the certificate as a
     hexadecimal string.
    :vartype sha256_thumbprint: str
    :ivar issuer_name: Issuer distinguished name.
    :vartype issuer_name: str
    :ivar not_before_utc: The date on which the certificate becomes valid.
    :vartype not_before_utc: datetime
    :ivar not_after_utc: The date on which the certificate is no longer valid.
    :vartype not_after_utc: datetime
    :ivar serial_number: The serial number.
    :vartype serial_number: str
    :ivar version: The X509 format version.
    :vartype version: int
    """

    _validation = {
        'subject_name': {'readonly': True},
        'sha1_thumbprint': {'readonly': True},
        'sha256_thumbprint': {'readonly': True},
        'issuer_name': {'readonly': True},
        'not_before_utc': {'readonly': True},
        'not_after_utc': {'readonly': True},
        'serial_number': {'readonly': True},
        'version': {'readonly': True},
    }

    _attribute_map = {
        'subject_name': {'key': 'subjectName', 'type': 'str'},
        'sha1_thumbprint': {'key': 'sha1Thumbprint', 'type': 'str'},
        'sha256_thumbprint': {'key': 'sha256Thumbprint', 'type': 'str'},
        'issuer_name': {'key': 'issuerName', 'type': 'str'},
        'not_before_utc': {'key': 'notBeforeUtc', 'type': 'iso-8601'},
        'not_after_utc': {'key': 'notAfterUtc', 'type': 'iso-8601'},
        'serial_number': {'key': 'serialNumber', 'type': 'str'},
        'version': {'key': 'version', 'type': 'int'},
    }

    def __init__(self, **kwargs) -> None:
        super(X509CertificateMetadata, self).__init__(**kwargs)
        self.subject_name = None
        self.sha1_thumbprint = None
        self.sha256_thumbprint = None
        self.issuer_name = None
        self.not_before_utc = None
        self.not_after_utc = None
        self.serial_number = None
        self.version = None
