parameters:
- name: architecture
  type: string
  default: 'x64'
- name: azureCLIVersion
  type: string
  default: released
  values:
  - min
  - released
  - msi
- name: 'testCentral'
  type: boolean
  default: true
- name: 'testADT'
  type: boolean
  default: true
- name: 'testDPS'
  type: boolean
  default: true
- name: 'testHub'
  type: boolean
  default: true
- name: 'testADU'
  type: boolean
  default: true
- name: 'maxParallelCentral'
  type: number
  default: 1
- name: 'maxParallelADT'
  type: number
  default: 1
- name: 'maxParallelDPS'
  type: number
  default: 1
- name: 'maxParallelHub'
  type: number
  default: 1
- name: 'maxParallelADU'
  type: number
  default: 1
- name: 'maxParallelUnit'
  type: number
  default: 1

jobs:

- job: 'testHub_job_1'
  timeoutInMinutes: 120
  displayName: 'Test IoT Hub - certificate, config, core, jobs, state'
  condition: and(succeeded(), eq('${{ parameters.testHub }}', true))
  strategy:
    matrix: $[ variables['pythonVersions'] ]
    maxParallel: ${{ parameters.maxParallelHub }}
  steps:
  - template: run-tests-parallel.yml
    parameters:
      path: 'azext_iot/tests/iothub/configurations azext_iot/tests/iothub/core azext_iot/tests/iothub/jobs azext_iot/tests/iothub/state'
      name: 'iot-hub-1'
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      pythonVersion: $(python)
      serviceConnection: $(AzureServiceConnection)

