parameters:
- name: pythonVersion
  type: string
  default: '3.8.x'
- name: pythonVersionsForTesting
  type: object
  default:
  - '3_6_x'
  - '3_8_x'
  - '3_9_x'
  - '3_10_x'
- name: architecture
  type: string
  default: 'x64'
- name: azureCLIVersion
  type: string
  default: released
  values:
  - min
  - released
  - msi
- name: azureSubscription
  type: string
  default: 'az_cli_nightly_conn'
- name: 'testCentral'
  type: boolean
  default: true
- name: 'testADT'
  type: boolean
  default: true
- name: 'testDPS'
  type: boolean
  default: true
- name: 'testHub'
  type: boolean
  default: true

jobs:

- job: 'testCentral'
  displayName: 'Test IoT Central'
  condition: and(succeeded(), eq('${{ parameters.testCentral }}', true))
  strategy:
    matrix: $[ variables['pythonVersions'] ]
    maxParallel: 2
  steps:
  - template: run-tests-parallel.yml
    parameters:
      path: 'azext_iot/tests/central'
      name: 'iot-central'
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      pythonVersion: ${{replace($(python), '_', '.')}}

- job: 'testADT'
  displayName: 'Test Azure DigitalTwins'
  condition: and(succeeded(), eq('${{ parameters.testADT }}', true))
  steps:
  - template: run-tests-parallel.yml
    parameters:
      path: 'azext_iot/tests/digitaltwins'
      name: 'azure-digitaltwins'
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      pythonVersion: ${{ parameters.pythonVersion }}

- job: 'testDPS'
  displayName: 'Test DPS'
  condition: and(succeeded(), eq('${{ parameters.testDPS }}', true))
  steps:
  - template: run-tests-parallel.yml
    parameters:
      path: 'azext_iot/tests/dps'
      name: 'device-provisioning-service'
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      pythonVersion: ${{ parameters.pythonVersion }}

- job: 'testHub_job_1'
  displayName: 'Test IoT Hub - config, core and jobs'
  condition: and(succeeded(), eq('${{ parameters.testHub }}', true))
  steps:
  - template: run-tests-parallel.yml
    parameters:
      path: 'azext_iot/tests/iothub/configurations azext_iot/tests/iothub/core azext_iot/tests/iothub/jobs'
      name: 'iot-hub-1'
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      pythonVersion: ${{ parameters.pythonVersion }}

- job: 'testHub_job_2'
  condition: and(succeeded(), eq('${{ parameters.testHub }}', true))
  displayName: 'Test IoT Hub - devices, messaging and modules'
  steps:
  - template: run-tests-parallel.yml
    parameters:
      path: 'azext_iot/tests/iothub/devices azext_iot/tests/iothub/messaging azext_iot/tests/iothub/modules'
      name: 'iot-hub-2'
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      pythonVersion: ${{ parameters.pythonVersion }}

- job: 'unitTests'
  displayName: 'Unit tests and code coverage'
  steps:
  - template: run-tests-parallel.yml
    parameters:
      azureCLIVersion: ${{ parameters.azureCLIVersion }}
      runIntTests: 'false'
      runUnitTests: 'true'
      pythonVersion: ${{ parameters.pythonVersion }}
