exclude: azext_iot/sdk/
repos:
  # Prevent python black hook from executing
  #- repo: https://github.com/psf/black
  #  rev: stable
  #  hooks:
  #    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
