dist: trusty
sudo: off
language: python
before_install:
  - chmod +x ./scripts/ci/test_source.sh
  - chmod +x ./scripts/ci/test_static.sh
  - chmod +x ./scripts/ci/test_clicore_linter.sh
install:
    - pip install -e .
    - pip install -r ./dev_requirements
jobs:
  include:
   - stage: verify
     env: PURPOSE='SourceUnitTests'
     script: ./scripts/ci/test_source.sh
     python: 3.6
   - stage: verify
     env: PURPOSE='CLICoreValidationTests'
     script: ./scripts/ci/test_clicore_linter.sh
     python: 3.6
