dist: trusty
sudo: off
language: python
before_install:
  - chmod +x ./scripts/ci/test_source.sh
install:
    - pip install pylint flake8 requests pytest pytest-mock pytest-ordering -q
jobs:
  include:
    - stage: verify
      env: PURPOSE='SourceTests'
      script: ./scripts/ci/test_source.sh
      python: 2.7
    - stage: verify
      env: PURPOSE='SourceTests'
      script: ./scripts/ci/test_source.sh
      python: 3.6
