# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Metadata(Model):
    """Metadata.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param last_updated_utc: The last time the properties were updated. In
     ISO8601 datetime format in UTC, for example, 2015-01-28T16:24:48.789Z.
    :type last_updated_utc: :class:`VariantValueDateTime
     <device_api.models.VariantValueDateTime>`
    :param last_updated_version: This SHOULD be null for Reported properties
     metadata and MUST not be null for Desired properties metadata.
    :type last_updated_version: long
    :ivar has_children: True if nested properies are present.
    :vartype has_children: bool
    :ivar nested: Nested properties.
    :vartype nested: dict
    """

    _validation = {
        'has_children': {'readonly': True},
        'nested': {'readonly': True},
    }

    _attribute_map = {
        'last_updated_utc': {'key': 'LastUpdatedUtc', 'type': 'VariantValueDateTime'},
        'last_updated_version': {'key': 'LastUpdatedVersion', 'type': 'long'},
        'has_children': {'key': 'HasChildren', 'type': 'bool'},
        'nested': {'key': 'Nested', 'type': '{Metadata}'},
    }

    def __init__(self, last_updated_utc=None, last_updated_version=None):
        self.last_updated_utc = last_updated_utc
        self.last_updated_version = last_updated_version
        self.has_children = None
        self.nested = None
