# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PropertyContainer(Model):
    """Container of desired and reported IoT Hub device twin properties.

    :param desired:
    :type desired: :class:`DeviceTwinProperties
     <device_api.models.DeviceTwinProperties>`
    :param reported:
    :type reported: :class:`DeviceTwinProperties
     <device_api.models.DeviceTwinProperties>`
    """

    _attribute_map = {
        'desired': {'key': 'desired', 'type': 'DeviceTwinProperties'},
        'reported': {'key': 'reported', 'type': 'DeviceTwinProperties'},
    }

    def __init__(self, desired=None, reported=None):
        self.desired = desired
        self.reported = reported
