# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class QuerySpecification(Model):
    """Query specification to retrieve information about device twins and jobs
    using a SQL-like language. See
    https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language
    for more information.

    :param query:
    :type query: str
    """

    _validation = {
        'query': {'required': True},
    }

    _attribute_map = {
        'query': {'key': 'query', 'type': 'str'},
    }

    def __init__(self, query):
        self.query = query
