# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegistryStatistics(Model):
    """Represents the device statistics gathered by IoT Hub. Contains the total
    number of device identities and a breakdown of the number of devices that
    are enabled and disabled.

    :param total_device_count:
    :type total_device_count: long
    :param enabled_device_count:
    :type enabled_device_count: long
    :param disabled_device_count:
    :type disabled_device_count: long
    """

    _validation = {
        'total_device_count': {'required': True},
        'enabled_device_count': {'required': True},
        'disabled_device_count': {'required': True},
    }

    _attribute_map = {
        'total_device_count': {'key': 'totalDeviceCount', 'type': 'long'},
        'enabled_device_count': {'key': 'enabledDeviceCount', 'type': 'long'},
        'disabled_device_count': {'key': 'disabledDeviceCount', 'type': 'long'},
    }

    def __init__(self, total_device_count, enabled_device_count, disabled_device_count):
        self.total_device_count = total_device_count
        self.enabled_device_count = enabled_device_count
        self.disabled_device_count = disabled_device_count
