# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ApiToken
    from ._models_py3 import ApiTokenCollection
    from ._models_py3 import Attestation
    from ._models_py3 import Collection
    from ._models_py3 import Device
    from ._models_py3 import DeviceCollection
    from ._models_py3 import DeviceCommand
    from ._models_py3 import DeviceCommandCollection
    from ._models_py3 import DeviceCredentials
    from ._models_py3 import DeviceTelemetry
    from ._models_py3 import DeviceTemplate
    from ._models_py3 import DeviceTemplateCollection
    from ._models_py3 import EmailUser
    from ._models_py3 import Permission
    from ._models_py3 import PermissionRolesItem
    from ._models_py3 import Role
    from ._models_py3 import RoleCollection
    from ._models_py3 import ServicePrincipalUser
    from ._models_py3 import SymmetricKey
    from ._models_py3 import SymmetricKeyAttestation
    from ._models_py3 import Tpm
    from ._models_py3 import TpmAttestation
    from ._models_py3 import User
    from ._models_py3 import UserCollection
    from ._models_py3 import X509
    from ._models_py3 import X509Attestation
    from ._models_py3 import X509Certificate
    from ._models_py3 import X509CertificateInfo
    from ._models_py3 import X509Certificates
except (SyntaxError, ImportError):
    from ._models import ApiToken  # type: ignore
    from ._models import ApiTokenCollection  # type: ignore
    from ._models import Attestation  # type: ignore
    from ._models import Collection  # type: ignore
    from ._models import Device  # type: ignore
    from ._models import DeviceCollection  # type: ignore
    from ._models import DeviceCommand  # type: ignore
    from ._models import DeviceCommandCollection  # type: ignore
    from ._models import DeviceCredentials  # type: ignore
    from ._models import DeviceTelemetry  # type: ignore
    from ._models import DeviceTemplate  # type: ignore
    from ._models import DeviceTemplateCollection  # type: ignore
    from ._models import EmailUser  # type: ignore
    from ._models import Permission  # type: ignore
    from ._models import PermissionRolesItem  # type: ignore
    from ._models import Role  # type: ignore
    from ._models import RoleCollection  # type: ignore
    from ._models import ServicePrincipalUser  # type: ignore
    from ._models import SymmetricKey  # type: ignore
    from ._models import SymmetricKeyAttestation  # type: ignore
    from ._models import Tpm  # type: ignore
    from ._models import TpmAttestation  # type: ignore
    from ._models import User  # type: ignore
    from ._models import UserCollection  # type: ignore
    from ._models import X509  # type: ignore
    from ._models import X509Attestation  # type: ignore
    from ._models import X509Certificate  # type: ignore
    from ._models import X509CertificateInfo  # type: ignore
    from ._models import X509Certificates  # type: ignore

__all__ = [
    'ApiToken',
    'ApiTokenCollection',
    'Attestation',
    'Collection',
    'Device',
    'DeviceCollection',
    'DeviceCommand',
    'DeviceCommandCollection',
    'DeviceCredentials',
    'DeviceTelemetry',
    'DeviceTemplate',
    'DeviceTemplateCollection',
    'EmailUser',
    'Permission',
    'PermissionRolesItem',
    'Role',
    'RoleCollection',
    'ServicePrincipalUser',
    'SymmetricKey',
    'SymmetricKeyAttestation',
    'Tpm',
    'TpmAttestation',
    'User',
    'UserCollection',
    'X509',
    'X509Attestation',
    'X509Certificate',
    'X509CertificateInfo',
    'X509Certificates',
]
