# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DirectMethodTest(Model):
    """DirectMethodTest.

    :param method_name:
    :type method_name: str
    :param payload:
    :type payload: str
    :param validation_timeout:
    :type validation_timeout: int
    :param is_mandatory:
    :type is_mandatory: bool
    :param should_validate:
    :type should_validate: bool
    """

    _attribute_map = {
        'method_name': {'key': 'methodName', 'type': 'str'},
        'payload': {'key': 'payload', 'type': 'str'},
        'validation_timeout': {'key': 'validationTimeout', 'type': 'int'},
        'is_mandatory': {'key': 'isMandatory', 'type': 'bool'},
        'should_validate': {'key': 'shouldValidate', 'type': 'bool'},
    }

    def __init__(self, **kwargs):
        super(DirectMethodTest, self).__init__(**kwargs)
        self.method_name = kwargs.get('method_name', None)
        self.payload = kwargs.get('payload', None)
        self.validation_timeout = kwargs.get('validation_timeout', None)
        self.is_mandatory = kwargs.get('is_mandatory', None)
        self.should_validate = kwargs.get('should_validate', None)
