# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ModelDefinitionSnapshot(Model):
    """ModelDefinitionSnapshot.

    :param id:
    :type id: str
    :param content:
    :type content: str
    :param resolution_source: Possible values include: 'Unknown',
     'GlobalRepository', 'PrivateRepository', 'UserUploads'
    :type resolution_source: str or ~product.models.enum
    :param interface_snapshots:
    :type interface_snapshots:
     list[~product.models.InterfaceDefinitionSnapshot]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'content': {'key': 'content', 'type': 'str'},
        'resolution_source': {'key': 'resolutionSource', 'type': 'str'},
        'interface_snapshots': {'key': 'interfaceSnapshots', 'type': '[InterfaceDefinitionSnapshot]'},
    }

    def __init__(self, *, id: str=None, content: str=None, resolution_source=None, interface_snapshots=None, **kwargs) -> None:
        super(ModelDefinitionSnapshot, self).__init__(**kwargs)
        self.id = id
        self.content = content
        self.resolution_source = resolution_source
        self.interface_snapshots = interface_snapshots
