# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NewTaskPayload(Model):
    """NewTaskPayload.

    :param task_type: Possible values include: 'QueueTestRun',
     'GenerateTestCases'
    :type task_type: str or ~product.models.enum
    """

    _attribute_map = {
        'task_type': {'key': 'taskType', 'type': 'str'},
    }

    def __init__(self, *, task_type=None, **kwargs) -> None:
        super(NewTaskPayload, self).__init__(**kwargs)
        self.task_type = task_type
