# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PropertyModel(Model):
    """PropertyModel.

    :param supplemental_types:
    :type supplemental_types: list[str]
    :param schema:
    :type schema: object
    :param writable:
    :type writable: bool
    :param supplemental_properties:
    :type supplemental_properties: dict[str, object]
    :param name:
    :type name: str
    :param comment:
    :type comment: str
    :param display_name:
    :type display_name: dict[str, str]
    :param id:
    :type id: str
    :param description:
    :type description: dict[str, str]
    :param language_version:
    :type language_version: int
    """

    _attribute_map = {
        'supplemental_types': {'key': 'supplementalTypes', 'type': '[str]'},
        'schema': {'key': 'schema', 'type': 'object'},
        'writable': {'key': 'writable', 'type': 'bool'},
        'supplemental_properties': {'key': 'supplementalProperties', 'type': '{object}'},
        'name': {'key': 'name', 'type': 'str'},
        'comment': {'key': 'comment', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': '{str}'},
        'id': {'key': 'id', 'type': 'str'},
        'description': {'key': 'description', 'type': '{str}'},
        'language_version': {'key': 'languageVersion', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(PropertyModel, self).__init__(**kwargs)
        self.supplemental_types = kwargs.get('supplemental_types', None)
        self.schema = kwargs.get('schema', None)
        self.writable = kwargs.get('writable', None)
        self.supplemental_properties = kwargs.get('supplemental_properties', None)
        self.name = kwargs.get('name', None)
        self.comment = kwargs.get('comment', None)
        self.display_name = kwargs.get('display_name', None)
        self.id = kwargs.get('id', None)
        self.description = kwargs.get('description', None)
        self.language_version = kwargs.get('language_version', None)
