# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TpmEnrollment(Model):
    """TpmEnrollment.

    :param scope_id:
    :type scope_id: str
    :param registration_id:
    :type registration_id: str
    :param endorsement_key:
    :type endorsement_key: str
    :param storage_root_key:
    :type storage_root_key: str
    """

    _attribute_map = {
        'scope_id': {'key': 'scopeId', 'type': 'str'},
        'registration_id': {'key': 'registrationId', 'type': 'str'},
        'endorsement_key': {'key': 'endorsementKey', 'type': 'str'},
        'storage_root_key': {'key': 'storageRootKey', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(TpmEnrollment, self).__init__(**kwargs)
        self.scope_id = kwargs.get('scope_id', None)
        self.registration_id = kwargs.get('registration_id', None)
        self.endorsement_key = kwargs.get('endorsement_key', None)
        self.storage_root_key = kwargs.get('storage_root_key', None)
