# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BulkOperation(Model):
    """Bulk operation.

    :param mode: Possible values include: 'create', 'update',
     'updateIfMatchETag', 'delete'
    :type mode: str or
     ~microsoft.azure.management.provisioningservices.models.enum
    :param enrollments:
    :type enrollments:
     list[~microsoft.azure.management.provisioningservices.models.Enrollment]
    """

    _validation = {
        'mode': {'required': True},
    }

    _attribute_map = {
        'mode': {'key': 'mode', 'type': 'str'},
        'enrollments': {'key': 'enrollments', 'type': '[Enrollment]'},
    }

    def __init__(self, mode, enrollments=None):
        super(BulkOperation, self).__init__()
        self.mode = mode
        self.enrollments = enrollments
