# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceRegistrationStatus(Model):
    """Device registration status.

    :param registration_id:
    :type registration_id: str
    :param created_date_time_utc:
    :type created_date_time_utc: datetime
    :param assigned_hub:
    :type assigned_hub: str
    :param device_id:
    :type device_id: str
    :param status: Possible values include: 'unassigned', 'assigning',
     'assigned', 'failed', 'disabled'
    :type status: str or
     ~microsoft.azure.management.provisioningservices.models.enum
    :param generation_id:
    :type generation_id: str
    :param last_updated_date_time_utc:
    :type last_updated_date_time_utc: datetime
    :param error_code:
    :type error_code: int
    :param error_message:
    :type error_message: str
    :param etag:
    :type etag: str
    """

    _validation = {
        'registration_id': {'required': True},
        'status': {'required': True},
    }

    _attribute_map = {
        'registration_id': {'key': 'registrationId', 'type': 'str'},
        'created_date_time_utc': {'key': 'createdDateTimeUtc', 'type': 'iso-8601'},
        'assigned_hub': {'key': 'assignedHub', 'type': 'str'},
        'device_id': {'key': 'deviceId', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'generation_id': {'key': 'generationId', 'type': 'str'},
        'last_updated_date_time_utc': {'key': 'lastUpdatedDateTimeUtc', 'type': 'iso-8601'},
        'error_code': {'key': 'errorCode', 'type': 'int'},
        'error_message': {'key': 'errorMessage', 'type': 'str'},
        'etag': {'key': 'etag', 'type': 'str'},
    }

    def __init__(self, registration_id, status, created_date_time_utc=None, assigned_hub=None, device_id=None, generation_id=None, last_updated_date_time_utc=None, error_code=None, error_message=None, etag=None):
        super(DeviceRegistrationStatus, self).__init__()
        self.registration_id = registration_id
        self.created_date_time_utc = created_date_time_utc
        self.assigned_hub = assigned_hub
        self.device_id = device_id
        self.status = status
        self.generation_id = generation_id
        self.last_updated_date_time_utc = last_updated_date_time_utc
        self.error_code = error_code
        self.error_message = error_message
        self.etag = etag
