# coding=utf-8
# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

from knack.log import get_logger
from knack.util import CLIError

from azext_iot.constants import CENTRAL_ENDPOINT
from azext_iot.central import services as central_services
from azext_iot.central.models.enum import Role
from azext_iot.sdk.central.iot_central_api_preview import IotCentralApiPreview
from azext_iot.central.services import _utility
from azext_iot.central.models.enum import Role, UserType

logger = get_logger(__name__)


class CentralUserProviderPreview:
    def __init__(self, cmd, app_id: str, token=None):
        """
        Provider for device APIs

        Args:
            cmd: command passed into az
            app_id: name of app (used for forming request URL)
            token: (OPTIONAL) authorization token to fetch device details from IoTC.
                MUST INCLUDE type (e.g. 'SharedAccessToken ...', 'Bearer ...')
                Useful in scenarios where user doesn't own the app
                therefore AAD token won't work, but a SAS token generated by owner will
        """
        self._cmd = cmd
        self._app_id = app_id
        self._token = token


    def get_user_list(
        self, central_dns_suffix=CENTRAL_ENDPOINT,
    ):
        token = _utility.get_token_credential(self._cmd)
        apiClient = IotCentralApiPreview(token, self._app_id, central_dns_suffix)
        
        return apiClient.users.list()


    def get_user(
        self, user_id, central_dns_suffix=CENTRAL_ENDPOINT,
    ):
        token = _utility.get_token_credential(self._cmd)
        apiClient = IotCentralApiPreview(token, self._app_id, central_dns_suffix)
        
        return apiClient.users.get(user_id)

    def delete_user(
        self, user_id, central_dns_suffix=CENTRAL_ENDPOINT,
    ):
        token = _utility.get_token_credential(self._cmd)
        apiClient = IotCentralApiPreview(token, self._app_id, central_dns_suffix)
        
        return apiClient.users.remove(user_id)

    def add_email(
        self,
        assignee: str,
        email: str,
        role: Role,
        central_dns_suffix=CENTRAL_ENDPOINT,
    ):
        if not email:
            raise CLIError("Must specify --email when adding a user by email")

        token = _utility.get_token_credential(self._cmd)
        apiClient = IotCentralApiPreview(token, self._app_id, central_dns_suffix)
        payload = {
            "email": email,
            "type": UserType.email.value,
            "roles": [{"role": role.value}],
        }
        return apiClient.users.set(assignee, payload)

    def add_service_principal(
        self,
        assignee: str,
        tenant_id: str,
        object_id: str,
        role: Role,
        central_dns_suffix=CENTRAL_ENDPOINT,
    ):
        if not tenant_id:
            raise CLIError("Must specify --tenant-id when adding a service principal")

        if not object_id:
            raise CLIError("Must specify --object-id when adding a service principal")
        token = _utility.get_token_credential(self._cmd)
        apiClient = IotCentralApiPreview(token, self._app_id, central_dns_suffix)

        payload = {
            "tenantId": tenant_id,
            "objectId": object_id,
            "type": UserType.service_principal.value,
            "roles": [{"role": role.value}],
        }

        return apiClient.users.set(assignee, payload)