# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NetworkRuleSetProperties(Model):
    """Network Rule Set Properties of IotHub.

    All required parameters must be populated in order to send to Azure.

    :param default_action: Default Action for Network Rule Set. Possible
     values include: 'Deny', 'Allow'. Default value: "Deny" .
    :type default_action: str or ~service.models.DefaultAction
    :param apply_to_built_in_event_hub_endpoint: Required. If True, then
     Network Rule Set is also applied to BuiltIn EventHub EndPoint of IotHub
    :type apply_to_built_in_event_hub_endpoint: bool
    :param ip_rules: Required. List of IP Rules
    :type ip_rules: list[~service.models.NetworkRuleSetIpRule]
    """

    _validation = {
        'apply_to_built_in_event_hub_endpoint': {'required': True},
        'ip_rules': {'required': True},
    }

    _attribute_map = {
        'default_action': {'key': 'defaultAction', 'type': 'str'},
        'apply_to_built_in_event_hub_endpoint': {'key': 'applyToBuiltInEventHubEndpoint', 'type': 'bool'},
        'ip_rules': {'key': 'ipRules', 'type': '[NetworkRuleSetIpRule]'},
    }

    def __init__(self, **kwargs):
        super(NetworkRuleSetProperties, self).__init__(**kwargs)
        self.default_action = kwargs.get('default_action', "Deny")
        self.apply_to_built_in_event_hub_endpoint = kwargs.get('apply_to_built_in_event_hub_endpoint', None)
        self.ip_rules = kwargs.get('ip_rules', None)
