# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ModelInformation(Model):
    """Model Metadata.

    :param comment: Gets or sets comments value in the model.
    :type comment: str
    :param description: Gets or sets description about the model.
    :type description: str
    :param display_name: Gets or sets display Name of the model.
    :type display_name: str
    :param model_id: Gets or sets model Identifier.
    :type model_id: str
    :param model_name: Gets or sets model Name.
    :type model_name: str
    :param version: Gets or sets modelVersion of the model.
    :type version: str
    :param model_type: Gets or sets model Definition Type. Possible values
     include: 'Interface', 'Undetermined'
    :type model_type: str or ~pnp.models.enum
    :param publisher_id: Gets or sets aad Tenant Id of the model publisher.
    :type publisher_id: str
    :param publisher_name: Gets or sets aad Tenant Name of the model
     publisher.
    :type publisher_name: str
    :param created_by: Gets or sets the identity of the user who created the
     model.
    :type created_by: str
    :param created_date: Gets or sets created Date and Time of the model.
    :type created_date: datetime
    :param updated_date: Gets or sets updated date and time of the model.
    :type updated_date: datetime
    :param model_state: Gets or sets the state of the model. - Created or
     Listed. Possible values include: 'Created', 'Listed'
    :type model_state: str or ~pnp.models.enum
    :param _etag: Gets or sets the e tag.
    :type _etag: str
    :param count_of_components: Gets or sets the number of components.
    :type count_of_components: int
    :param count_of_commands: Gets or sets the number of commands.
    :type count_of_commands: int
    :param count_of_telemetries: Gets or sets the number of telemetries.
    :type count_of_telemetries: int
    :param count_of_properties: Gets or sets the number of properties.
    :type count_of_properties: int
    :param count_of_relationships: Gets or sets the number of relationships.
    :type count_of_relationships: int
    :param count_of_extends: Gets or sets the number of extends.
    :type count_of_extends: int
    :param count_of_schemas: Gets or sets the number of schemas.
    :type count_of_schemas: int
    """

    _attribute_map = {
        'comment': {'key': 'comment', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'model_id': {'key': 'modelId', 'type': 'str'},
        'model_name': {'key': 'modelName', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'model_type': {'key': 'modelType', 'type': 'str'},
        'publisher_id': {'key': 'publisherId', 'type': 'str'},
        'publisher_name': {'key': 'publisherName', 'type': 'str'},
        'created_by': {'key': 'createdBy', 'type': 'str'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'updated_date': {'key': 'updatedDate', 'type': 'iso-8601'},
        'model_state': {'key': 'modelState', 'type': 'str'},
        '_etag': {'key': '_etag', 'type': 'str'},
        'count_of_components': {'key': 'countOfComponents', 'type': 'int'},
        'count_of_commands': {'key': 'countOfCommands', 'type': 'int'},
        'count_of_telemetries': {'key': 'countOfTelemetries', 'type': 'int'},
        'count_of_properties': {'key': 'countOfProperties', 'type': 'int'},
        'count_of_relationships': {'key': 'countOfRelationships', 'type': 'int'},
        'count_of_extends': {'key': 'countOfExtends', 'type': 'int'},
        'count_of_schemas': {'key': 'countOfSchemas', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(ModelInformation, self).__init__(**kwargs)
        self.comment = kwargs.get('comment', None)
        self.description = kwargs.get('description', None)
        self.display_name = kwargs.get('display_name', None)
        self.model_id = kwargs.get('model_id', None)
        self.model_name = kwargs.get('model_name', None)
        self.version = kwargs.get('version', None)
        self.model_type = kwargs.get('model_type', None)
        self.publisher_id = kwargs.get('publisher_id', None)
        self.publisher_name = kwargs.get('publisher_name', None)
        self.created_by = kwargs.get('created_by', None)
        self.created_date = kwargs.get('created_date', None)
        self.updated_date = kwargs.get('updated_date', None)
        self.model_state = kwargs.get('model_state', None)
        self._etag = kwargs.get('_etag', None)
        self.count_of_components = kwargs.get('count_of_components', None)
        self.count_of_commands = kwargs.get('count_of_commands', None)
        self.count_of_telemetries = kwargs.get('count_of_telemetries', None)
        self.count_of_properties = kwargs.get('count_of_properties', None)
        self.count_of_relationships = kwargs.get('count_of_relationships', None)
        self.count_of_extends = kwargs.get('count_of_extends', None)
        self.count_of_schemas = kwargs.get('count_of_schemas', None)
