# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .error_details import ErrorDetails, ErrorDetailsException

__all__ = [
    'ErrorDetails',
    'ErrorDetailsException',
]
