# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class FileUploadState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The state of the file upload configuration."""

    PENDING = "pending"
    UPDATING = "updating"
    DELETING = "deleting"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
