# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceCapabilities(Model):
    """Device capabilities.

    :param iot_edge: IoT Edge capability
    :type iot_edge: bool
    """

    _validation = {
        'iot_edge': {'required': True},
    }

    _attribute_map = {
        'iot_edge': {'key': 'iotEdge', 'type': 'bool'},
    }

    def __init__(self, iot_edge):
        super(DeviceCapabilities, self).__init__()
        self.iot_edge = iot_edge
