# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EnrollmentGroup(Model):
    """Enrollment group record.

    :param enrollment_group_id: Enrollment Group ID.
    :type enrollment_group_id: str
    :param attestation: Attestation method used by the device.
    :type attestation:
     ~microsoft.azure.management.provisioningservices.models.GroupAttestationMechanism
    :param iot_hub_host_name: The Iot Hub host name.
    :type iot_hub_host_name: str
    :param initial_twin: Initial device twin.
    :type initial_twin:
     ~microsoft.azure.management.provisioningservices.models.InitialTwin
    :param etag: The entity tag associated with the resource.
    :type etag: str
    :param provisioning_status: The provisioning status. Possible values
     include: 'enabled', 'disabled'. Default value: "1" .
    :type provisioning_status: str or
     ~microsoft.azure.management.provisioningservices.models.enum
    :param reprovision_policy: The behavior when a device is re-provisioned to
     an IoT hub.
    :type reprovision_policy:
     ~microsoft.azure.management.provisioningservices.models.ReprovisionPolicy
    :param created_date_time_utc: The DateTime this resource was created.
    :type created_date_time_utc: datetime
    :param last_updated_date_time_utc: The DateTime this resource was last
     updated.
    :type last_updated_date_time_utc: datetime
    :param allocation_policy: The allocation policy of this resource.
     Overrides the tenant level allocation policy. Possible values include:
     'hashed', 'geoLatency', 'static'
    :type allocation_policy: str or
     ~microsoft.azure.management.provisioningservices.models.enum
    :param iot_hubs: The list of names of IoT hubs the device(s) in this
     resource can be allocated to. Must be a subset of tenant level list of IoT
     hubs.
    :type iot_hubs: list[str]
    """

    _validation = {
        'enrollment_group_id': {'required': True},
        'attestation': {'required': True},
    }

    _attribute_map = {
        'enrollment_group_id': {'key': 'enrollmentGroupId', 'type': 'str'},
        'attestation': {'key': 'attestation', 'type': 'GroupAttestationMechanism'},
        'iot_hub_host_name': {'key': 'iotHubHostName', 'type': 'str'},
        'initial_twin': {'key': 'initialTwin', 'type': 'InitialTwin'},
        'etag': {'key': 'etag', 'type': 'str'},
        'provisioning_status': {'key': 'provisioningStatus', 'type': 'str'},
        'reprovision_policy': {'key': 'reprovisionPolicy', 'type': 'ReprovisionPolicy'},
        'created_date_time_utc': {'key': 'createdDateTimeUtc', 'type': 'iso-8601'},
        'last_updated_date_time_utc': {'key': 'lastUpdatedDateTimeUtc', 'type': 'iso-8601'},
        'allocation_policy': {'key': 'allocationPolicy', 'type': 'str'},
        'iot_hubs': {'key': 'iotHubs', 'type': '[str]'},
    }

    def __init__(self, enrollment_group_id, attestation, iot_hub_host_name=None, initial_twin=None, etag=None, provisioning_status="1", reprovision_policy=None, created_date_time_utc=None, last_updated_date_time_utc=None, allocation_policy=None, iot_hubs=None):
        super(EnrollmentGroup, self).__init__()
        self.enrollment_group_id = enrollment_group_id
        self.attestation = attestation
        self.iot_hub_host_name = iot_hub_host_name
        self.initial_twin = initial_twin
        self.etag = etag
        self.provisioning_status = provisioning_status
        self.reprovision_policy = reprovision_policy
        self.created_date_time_utc = created_date_time_utc
        self.last_updated_date_time_utc = last_updated_date_time_utc
        self.allocation_policy = allocation_policy
        self.iot_hubs = iot_hubs
