# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class InitialTwinProperties(Model):
    """InitialTwinProperties.

    :param desired: Gets and sets the InitialTwin desired properties.
    :type desired:
     ~microsoft.azure.management.provisioningservices.models.TwinCollection
    """

    _attribute_map = {
        'desired': {'key': 'desired', 'type': 'TwinCollection'},
    }

    def __init__(self, desired=None):
        super(InitialTwinProperties, self).__init__()
        self.desired = desired
