# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Metadata(Model):
    """Metadata.

    :param last_updated:
    :type last_updated: datetime
    :param last_updated_version: This SHOULD be null for Reported properties
     metadata and MUST not be null for Desired properties metadata.
    :type last_updated_version: long
    """

    _attribute_map = {
        'last_updated': {'key': 'lastUpdated', 'type': 'iso-8601'},
        'last_updated_version': {'key': 'lastUpdatedVersion', 'type': 'long'},
    }

    def __init__(self, last_updated=None, last_updated_version=None):
        super(Metadata, self).__init__()
        self.last_updated = last_updated
        self.last_updated_version = last_updated_version
