# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeviceTwinInfo(Model):
    """Container of IoT Hub device twin properties and their accessors.

    :param device_id: The deviceId uniquely identifies the device in the IoT
     hub's identity registry. A case-sensitive string (up to 128 char long) of
     ASCII 7-bit alphanumeric chars + {'-', ':', '.', '+', '%', '_', '#', '*',
     '?', '!', '(', ')', ',', '=', '@', ';', '$', '''}.
    :type device_id: str
    :param last_activity_time_utc: The last time the device connected,
     received or sent a message. In ISO8601 datetime format in UTC, for
     example, 2015-01-28T16:24:48.789Z. This does not update if the device uses
     the HTTP/1 protocol to perform messaging operations.
    :type last_activity_time_utc: :class:`VariantValueDateTime
     <device_twin.models.VariantValueDateTime>`
    :param is_connected: Indicates if the device is currently connected to the
     IoT hub or not.
    :type is_connected: bool
    :param last_connected_time_utc: The last time the device connected to the
     IoT hub. In ISO8601 datetime format in UTC, for example,
     2015-01-28T16:24:48.789Z. This does not update if the device uses the
     HTTP/1 protocol to perform messaging operations.
    :type last_connected_time_utc: :class:`VariantValueDateTime
     <device_twin.models.VariantValueDateTime>`
    :param version: Version for device twin, including tags and desired
     properties
    :type version: long
    :param tags: A JSON document read and written by the solution back end.
     Tags are not visible to device apps.
    :type tags: dict
    :param desired_properties: Used in conjunction with reported properties to
     synchronize device configuration or condition. Desired properties can only
     be set by the solution back end and can be read by the device app. The
     device app can also be notified in real time of changes on the desired
     properties.
    :type desired_properties: :class:`DeviceTwinProperties
     <device_twin.models.DeviceTwinProperties>`
    :param reported_properties: Used in conjunction with desired properties to
     synchronize device configuration or condition. Reported properties can
     only be set by the device app and can be read and queried by the solution
     back end.
    :type reported_properties: :class:`DeviceTwinProperties
     <device_twin.models.DeviceTwinProperties>`
    :param provisioning_state: Provisioning state of device twin. Possible
     values include: 'Creating', 'Deleting', 'Active', 'Deleted'
    :type provisioning_state: str or :class:`ProvisioningState
     <device_twin.models.ProvisioningState>`
    """

    _validation = {
        'device_id': {'pattern': "^[A-Za-z0-9\-:.+%_#*?!(),=@;$']{1,128}$"},
    }

    _attribute_map = {
        'device_id': {'key': 'DeviceId', 'type': 'str'},
        'last_activity_time_utc': {'key': 'LastActivityTimeUtc', 'type': 'VariantValueDateTime'},
        'is_connected': {'key': 'IsConnected', 'type': 'bool'},
        'last_connected_time_utc': {'key': 'LastConnectedTimeUtc', 'type': 'VariantValueDateTime'},
        'version': {'key': 'Version', 'type': 'long'},
        'tags': {'key': 'Tags', 'type': '{object}'},
        'desired_properties': {'key': 'DesiredProperties', 'type': 'DeviceTwinProperties'},
        'reported_properties': {'key': 'ReportedProperties', 'type': 'DeviceTwinProperties'},
        'provisioning_state': {'key': 'ProvisioningState', 'type': 'str'},
    }

    def __init__(self, device_id=None, last_activity_time_utc=None, is_connected=None, last_connected_time_utc=None, version=None, tags=None, desired_properties=None, reported_properties=None, provisioning_state=None):
        self.device_id = device_id
        self.last_activity_time_utc = last_activity_time_utc
        self.is_connected = is_connected
        self.last_connected_time_utc = last_connected_time_utc
        self.version = version
        self.tags = tags
        self.desired_properties = desired_properties
        self.reported_properties = reported_properties
        self.provisioning_state = provisioning_state
