# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import ADGroupUser
from ._models import ApiToken
from ._models import Attestation
from ._models import BarChartConfiguration
from ._models import BlobStorageV1Destination
from ._models import BlobStorageV1DestinationAuth
from ._models import BlobStorageV1DestinationConnectionStringAuth
from ._models import BlobStorageV1DestinationSystemAssignedManagedIdentityAuth
from ._models import CapabilityJobData
from ._models import ChartFormatConfiguration
from ._models import CloudPropertyJobData
from ._models import Collection
from ._models import CommandConfiguration
from ._models import CommandJobData
from ._models import CommandTileConfiguration
from ._models import CountQueryRangeConfiguration
from ._models import Dashboard
from ._models import DataExplorerTileConfiguration
from ._models import DataExplorerV1Destination
from ._models import DataExplorerV1DestinationAuth
from ._models import DataExplorerV1DestinationServicePrincipalAuth
from ._models import DataExplorerV1DestinationSystemAssignedManagedIdentityAuth
from ._models import DataExportError
from ._models import DataExportStatus
from ._models import DateJobScheduleEnd
from ._models import Destination
from ._models import DestinationExport
from ._models import DestinationReference
from ._models import Device
from ._models import DeviceCommand
from ._models import DeviceCountTileConfiguration
from ._models import DeviceCredentials
from ._models import DeviceGroup
from ._models import DeviceRelationship
from ._models import DeviceRelationshipCollection
from ._models import DeviceTelemetry
from ._models import DeviceTemplate
from ._models import DeviceTemplateMigrationJobData
from ._models import EmailUser
from ._models import Enrichment
from ._models import EnrollmentGroup
from ._models import Error
from ._models import ErrorDetails
from ._models import EventChartConfiguration
from ._models import EventHistoryChartConfiguration
from ._models import EventHubsV1Destination
from ._models import EventHubsV1DestinationAuth
from ._models import EventHubsV1DestinationConnectionStringAuth
from ._models import EventHubsV1DestinationSystemAssignedManagedIdentityAuth
from ._models import Export
from ._models import ExportDestination
from ._models import ExternalContentTileConfiguration
from ._models import FileUpload
from ._models import GroupAttestation
from ._models import GroupSymmetricKeyAttestation
from ._models import GroupTileConfiguration
from ._models import GroupX509Attestation
from ._models import HeatMapConfiguration
from ._models import ImageTileConfiguration
from ._models import ImageTileConfigurationFormat
from ._models import Job
from ._models import JobBatch
from ._models import JobCancellationThreshold
from ._models import JobData
from ._models import JobDeviceStatus
from ._models import JobProgress
from ._models import JobSchedule
from ._models import JobScheduleEnd
from ._models import KpiTileConfiguration
from ._models import LabelTileConfiguration
from ._models import LineChartConfiguration
from ._models import LkvTileConfiguration
from ._models import MapFormatConfiguration
from ._models import MapPropertyConfiguration
from ._models import MapTelemetryConfiguration
from ._models import MapTileConfiguration
from ._models import MarkdownTileConfiguration
from ._models import OccurrencesJobScheduleEnd
from ._models import Organization
from ._models import Permission
from ._models import PieChartConfiguration
from ._models import PropertyJobData
from ._models import PropertyTileConfiguration
from ._models import QueryRangeConfiguration
from ._models import QueryRequest
from ._models import QueryResponse
from ._models import Role
from ._models import RoleAssignment
from ._models import ScheduledJob
from ._models import ServiceBusQueueV1Destination
from ._models import ServiceBusQueueV1DestinationAuth
from ._models import ServiceBusQueueV1DestinationConnectionStringAuth
from ._models import ServiceBusQueueV1DestinationSystemAssignedManagedIdentityAuth
from ._models import ServiceBusTopicV1Destination
from ._models import ServiceBusTopicV1DestinationAuth
from ._models import ServiceBusTopicV1DestinationConnectionStringAuth
from ._models import ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth
from ._models import ServicePrincipalUser
from ._models import SigningX509
from ._models import SigningX509Certificate
from ._models import SigningX509Certificates
from ._models import StateChartConfiguration
from ._models import StateHistoryChartConfiguration
from ._models import SymmetricKey
from ._models import SymmetricKeyAttestation
from ._models import TextFormatConfiguration
from ._models import Tile
from ._models import TileCapability
from ._models import TileCapabilityConfiguration
from ._models import TileConfiguration
from ._models import TimeQueryRangeConfiguration
from ._models import Tpm
from ._models import TpmAttestation
from ._models import User
from ._models import WebhookV1Destination
from ._models import WebhookV1DestinationAuth
from ._models import WebhookV1DestinationCustomization
from ._models import WebhookV1DestinationHeaderAuth
from ._models import WebhookV1DestinationOAuth
from ._models import X509
from ._models import X509Attestation
from ._models import X509Certificate
from ._models import X509CertificateInfo
from ._models import X509Certificates
from ._models import X509VerificationCertificate
from ._models import X509VerificationCode

from ._enums import CapabilityAggregateType
from ._enums import CertificateEntry
from ._enums import DestinationSource
from ._enums import EnrollmentGroupType
from ._enums import FileUploadState
from ._enums import JobBatchType
from ._enums import JobCancellationThresholdType
from ._enums import JobRecurrence
from ._enums import OAuthRequestType
from ._enums import TileTimeRangeDuration
from ._enums import TileTimeRangeResolution
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "ADGroupUser",
    "ApiToken",
    "Attestation",
    "BarChartConfiguration",
    "BlobStorageV1Destination",
    "BlobStorageV1DestinationAuth",
    "BlobStorageV1DestinationConnectionStringAuth",
    "BlobStorageV1DestinationSystemAssignedManagedIdentityAuth",
    "CapabilityJobData",
    "ChartFormatConfiguration",
    "CloudPropertyJobData",
    "Collection",
    "CommandConfiguration",
    "CommandJobData",
    "CommandTileConfiguration",
    "CountQueryRangeConfiguration",
    "Dashboard",
    "DataExplorerTileConfiguration",
    "DataExplorerV1Destination",
    "DataExplorerV1DestinationAuth",
    "DataExplorerV1DestinationServicePrincipalAuth",
    "DataExplorerV1DestinationSystemAssignedManagedIdentityAuth",
    "DataExportError",
    "DataExportStatus",
    "DateJobScheduleEnd",
    "Destination",
    "DestinationExport",
    "DestinationReference",
    "Device",
    "DeviceCommand",
    "DeviceCountTileConfiguration",
    "DeviceCredentials",
    "DeviceGroup",
    "DeviceRelationship",
    "DeviceRelationshipCollection",
    "DeviceTelemetry",
    "DeviceTemplate",
    "DeviceTemplateMigrationJobData",
    "EmailUser",
    "Enrichment",
    "EnrollmentGroup",
    "Error",
    "ErrorDetails",
    "EventChartConfiguration",
    "EventHistoryChartConfiguration",
    "EventHubsV1Destination",
    "EventHubsV1DestinationAuth",
    "EventHubsV1DestinationConnectionStringAuth",
    "EventHubsV1DestinationSystemAssignedManagedIdentityAuth",
    "Export",
    "ExportDestination",
    "ExternalContentTileConfiguration",
    "FileUpload",
    "GroupAttestation",
    "GroupSymmetricKeyAttestation",
    "GroupTileConfiguration",
    "GroupX509Attestation",
    "HeatMapConfiguration",
    "ImageTileConfiguration",
    "ImageTileConfigurationFormat",
    "Job",
    "JobBatch",
    "JobCancellationThreshold",
    "JobData",
    "JobDeviceStatus",
    "JobProgress",
    "JobSchedule",
    "JobScheduleEnd",
    "KpiTileConfiguration",
    "LabelTileConfiguration",
    "LineChartConfiguration",
    "LkvTileConfiguration",
    "MapFormatConfiguration",
    "MapPropertyConfiguration",
    "MapTelemetryConfiguration",
    "MapTileConfiguration",
    "MarkdownTileConfiguration",
    "OccurrencesJobScheduleEnd",
    "Organization",
    "Permission",
    "PieChartConfiguration",
    "PropertyJobData",
    "PropertyTileConfiguration",
    "QueryRangeConfiguration",
    "QueryRequest",
    "QueryResponse",
    "Role",
    "RoleAssignment",
    "ScheduledJob",
    "ServiceBusQueueV1Destination",
    "ServiceBusQueueV1DestinationAuth",
    "ServiceBusQueueV1DestinationConnectionStringAuth",
    "ServiceBusQueueV1DestinationSystemAssignedManagedIdentityAuth",
    "ServiceBusTopicV1Destination",
    "ServiceBusTopicV1DestinationAuth",
    "ServiceBusTopicV1DestinationConnectionStringAuth",
    "ServiceBusTopicV1DestinationSystemAssignedManagedIdentityAuth",
    "ServicePrincipalUser",
    "SigningX509",
    "SigningX509Certificate",
    "SigningX509Certificates",
    "StateChartConfiguration",
    "StateHistoryChartConfiguration",
    "SymmetricKey",
    "SymmetricKeyAttestation",
    "TextFormatConfiguration",
    "Tile",
    "TileCapability",
    "TileCapabilityConfiguration",
    "TileConfiguration",
    "TimeQueryRangeConfiguration",
    "Tpm",
    "TpmAttestation",
    "User",
    "WebhookV1Destination",
    "WebhookV1DestinationAuth",
    "WebhookV1DestinationCustomization",
    "WebhookV1DestinationHeaderAuth",
    "WebhookV1DestinationOAuth",
    "X509",
    "X509Attestation",
    "X509Certificate",
    "X509CertificateInfo",
    "X509Certificates",
    "X509VerificationCertificate",
    "X509VerificationCode",
    "CapabilityAggregateType",
    "CertificateEntry",
    "DestinationSource",
    "EnrollmentGroupType",
    "FileUploadState",
    "JobBatchType",
    "JobCancellationThresholdType",
    "JobRecurrence",
    "OAuthRequestType",
    "TileTimeRangeDuration",
    "TileTimeRangeResolution",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
