# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none

# Run daily at 5 am (Pacific).
schedules:
- cron: "0 13 * * *"
  displayName: 'Daily Cleanup'
  branches:
    include:
    - dev
  always: true


parameters:
- name: variableGroup
  type: string
  default: 'cleanup_variables'


variables:
  - group: ${{ parameters.variableGroup }}


steps:
- checkout: none

- task: AzureCLI@2
  continueOnError: true
  displayName: 'Delete Test resources'
  inputs:
    azureSubscription: $(AzureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      names=($(EXCLUSIONS))
      query=$(printf '[?name!='"'"%q"'"']|' "${names[@]}")
      echo "Resources found to delete:"
      az resource list -g $(RESOURCE_GROUP) --query "$query[*].id"
      resources=$(az resource list -g $(RESOURCE_GROUP) --query "$query[*].id" -o tsv)
      echo "Deleting Resources"
      # az resource delete --ids $resources
