# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none

# Run daily at 5 am (Pacific).
schedules:
- cron: "0 13 * * *"
  displayName: 'Daily Cleanup'
  branches:
    include:
    - dev
  always: true


parameters:
- name: resourceGroupVar
  type: string
  default: 'ResourceGroup'
- name: exclusionsVar
  type: string
  default: 'Exclusions'


variables:
  - name: resourceGroup
    value: $[variables.${{ parameters.resourceGroupVar }}]
  - name: exclusions
    value: $[variables.${{ parameters.exclusionsVar }}]


steps:
- checkout: none

- task: AzureCLI@2
  continueOnError: true
  displayName: 'Delete Test resources'
  inputs:
    azureSubscription: $(AzureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      names=($EXCLUSIONS)
      query=$(printf '[?name!='"'"%q"'"']|' "${names[@]}")
      echo $query
      echo "Resources found to delete:"
      az resource list -g "$RESOURCEGROUP" --query "$query[*].id"
      resources=$(az resource list -g "$RESOURCEGROUP" --query "$query[*].id" -o tsv)
      echo "Deleting Resources"
      az resource delete --ids $resources
  env:
    RESOURCEGROUP: $(resourceGroup)
    EXCLUSIONS: $(exclusions)
