# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none

# Run daily at 5 am (Pacific).
schedules:
- cron: "0 13 * * *"
  displayName: 'Daily Cleanup'
  branches:
    include:
    - dev
  always: true

parameters:
- name: resourceGroup
  type: string
  default: 'cli-int-test-rg'
- name: exclusions
  type: string
  default: 'iotintteststandard azcliintteststorage az-cli-int-test-servicebus-namespace az-cli-int-test-eventgrid az-cli-int-test-eventhub-namespace'


steps:
- checkout: none

- task: AzureCLI@2
  continueOnError: true
  displayName: 'Delete Test resources'
  inputs:
    azureSubscription: $(AzureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      names=(${{ parameters.exclusions }})
      query=$(printf '[?name!='"'"%q"'"']|' "${names[@]}")
      echo "Resources found to delete:"
      az resource list -g ${{ parameters.resourceGroup }} --query "$query[*].id"
      resources=$(az resource list -g ${{ parameters.resourceGroup }} --query "$query[*].id" -o tsv)
      echo "Deleting Resources"
      az resource delete --ids $resources
