# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none

# Run weekly at midnight (Pacific).
# schedules:
# - cron: "0 8 * * 1"
#   displayName: 'Weekly Cleanup'
#   branches:
#     include:
#     - dev

parameters:
- name: resourceGroup
  type: string
  default: 'cli-int-test-rg'
- name: servicePrincipal
  type: string
  default: 'cli-int-test-rg'
- name: exclusions
  type: string
  default: 'iotintteststandard azcliintteststorage az-cli-int-test-servicebus-namespace az-cli-int-test-eventgrid az-cli-int-test-eventhub-namespace'


steps:
- task: AzureCLI@2
  continueOnError: true
  displayName: 'Delete Test resources'
  inputs:
    azureSubscription: $(AzureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      names=(iotintteststandard azcliintteststorage az-cli-int-test-servicebus-namespace az-cli-int-test-eventgrid az-cli-int-test-eventhub-namespace)
      query=$(printf '[?name!='"'"%q"'"']|' "${names[@]}")
      resources=$(az resource list -g cli-int-test-rg --query "$query|[*].id" -o tsv)
      echo "Deleting Resources"
      echo $resources
      az resource delete --ids $resources
