# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none

# Run nightly at midnight (Pacific).
schedules:
- cron: "0 8 * * *"
  displayName: 'Nightly Integration Build'
  branches:
    include:
    - dev

parameters:
- name: variableGroup
  type: string
  default: 'aziotcli_test_nightly'
- name: vmImage
  type: string
  default: 'ubuntu-18.04'
  values:
  - 'ubuntu-18.04'
  - 'ubuntu-latest'
- name: pythonVersion
  displayName: 'Python version for building wheel, KPIs'
  type: string
  default: '3.8.x'
  values:
  - '3.6.x'
  - '3.8.x'
  - '3.9.x'
- name: pythonVersionsTestingMatrix
  type: object
  default: >
    {
      Python36: 
      {
        python: '3.6.x'
      },
      Python38: 
      {
        python: '3.8.x'
      },
      Python39: 
      {
        python: '3.9.x'
      },
      Python310: 
      {
        python: '3.10.x'
      }
- name: architecture
  type: string
  default: 'x64'
- name: 'testCentral'
  type: boolean
  default: true
- name: 'testADT'
  type: boolean
  default: true
- name: 'testDPS'
  type: boolean
  default: true
- name: 'testHub'
  type: boolean
  default: true

variables:
  - group: ${{ parameters.variableGroup }}
  - name: pythonVersion
    value: ${{ parameters.pythonVersion }}
  - name: architecture
    value: ${{ parameters.architecture }}

stages:
  - stage: 'build'
    displayName: 'Build and Publish Artifacts'
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:

    - job: 'Build_Publish_Azure_IoT_CLI_Extension'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.pythonVersion }}
          architecture: ${{ parameters.architecture }}

      - template: templates/setup-ci-machine.yml

      - template: templates/build-publish-azure-iot-cli-extension.yml

    - job: 'Build_Publish_Azure_CLI_Test_SDK'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.pythonVersion }}
          architecture: ${{ parameters.architecture }}

      - template: templates/setup-ci-machine.yml

      - template: templates/build-publish-azure-cli-test-sdk.yml

    - job: 'recordVersion'
      displayName: 'Install and verify version'
      dependsOn: [Build_Publish_Azure_IoT_CLI_Extension, Build_Publish_Azure_CLI_Test_SDK]
      steps:
      - template: templates/setup-dev-test-env.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
          architecture: ${{ parameters.architecture }}

      - template: templates/install-and-record-version.yml
  
  - stage: 'test_min'
    displayName: 'Run all tests with min CLI'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: build
    variables:
      pythonVersions: ${{ parameters.pythonVersionsTestingMatrix }}
    jobs:
    - template: templates/trigger-tests.yml
      parameters:
        azureCLIVersion: min
        pythonVersion: ${{replace(python_version, '_', '.')}}
        testADT: ${{ parameters.testADT }}
        testCentral: ${{ parameters.testCentral }}
        testDPS: ${{ parameters.testDPS }}
        testHub: ${{ parameters.testHub }}
  
  - stage: 'test_msi'
    displayName: 'Run all tests against Windows MSI install'
    pool:
      vmImage: 'windows-2019'
    dependsOn: test_min
    jobs:
    - template: templates/trigger-tests.yml
      parameters:
        azureCLIVersion: msi
        testADT: ${{ parameters.testADT }}
        testCentral: ${{ parameters.testCentral }}
        testDPS: ${{ parameters.testDPS }}
        testHub: ${{ parameters.testHub }}
          
  - stage: 'kpi'
    displayName: 'Build KPIs'
    dependsOn: [build, test_msi, test_min]
    jobs:
    - job: 'calculateCodeCoverage'
      displayName: 'Calculate distributed code coverage'
      steps:
      - template: templates/calculate-code-coverage.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
          architecture: ${{ parameters.architecture }}
