# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none

parameters:
  - name: rootCommand
    type: string
    default: "iot"
  - name: linuxImage
    type: string
    default: "ubuntu-22.04"
    values:
      - "ubuntu-22.04"
      - "ubuntu-latest"

jobs:
  - job: "build_and_publish_azure_iot_cli_ext"
    pool:
      vmImage: ${{ parameters.linuxImage }}

    steps:
      - template: templates/setup-python.yml
      - template: templates/build-publish-azure-iot-cli-extension.yml
      - template: templates/install-azure-cli-released.yml
      - template: templates/download-install-local-azure-iot-cli-extension.yml
      - template: templates/set-pythonpath.yml
      - template: templates/generate-publish-help-documentation.yml
        parameters:
          rootCommand: ${{ parameters.rootCommand }}
