# Copyright (c) Microsoft Corporation. All rights reserved.

# Required for schedule only trigger
trigger: none
pr: none


parameters:
- name: rootCommand
  type: string
  default: 'iot'
- name: linuxImage
  type: string
  default: 'ubuntu-20.04'
  values:
  - 'ubuntu-18.04'
  - 'ubuntu-20.04'
  - 'ubuntu-22.04'
  - 'ubuntu-latest'


jobs:
  - job: 'build_and_publish_azure_iot_cli_ext'
    pool:
      vmImage: ${{ parameters.linuxImage }}

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        architecture: 'x64'

    - template: templates/setup-ci-machine.yml
    - template: templates/build-publish-azure-iot-cli-extension.yml

  - job: 'build_and_publish_azure_cli_test_sdk'
    pool:
      vmImage: ${{ parameters.linuxImage }}

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        architecture: 'x64'

    - template: templates/setup-ci-machine.yml
    - template: templates/build-publish-azure-cli-test-sdk.yml

  - job: 'Record_Version_Generate_Help'
    displayName: 'Install and verify version'
    dependsOn: [build_and_publish_azure_iot_cli_ext, build_and_publish_azure_cli_test_sdk]
    steps:
    - template: templates/setup-dev-test-env.yml
      parameters:
        pythonVersion: '3.8'
        architecture: 'x64'

    - template: templates/install-and-record-version.yml

    - template: templates/generate-publish-help-documentation.yml
      parameters:
        rootCommand: ${{ parameters.rootCommand }}
