trigger: none
pr: none

parameters:
- name: python39
  displayName: 'Test Python 3.9'
  type: boolean
  default: true
- name: python310
  displayName: 'Test Python 3.10'
  type: boolean
  default: true
- name: python311
  displayName: 'Test Python 3.11'
  type: boolean
  default: true
- name: python311
  displayName: 'Test Python 3.12'
  type: boolean
  default: true
- name: azdev
  displayName: 'Test development CLI'
  type: boolean
  default: true
- name: azmin
  displayName: 'Test minimum supported CLI'
  type: boolean
  default: true
- name: azcur
  displayName: 'Test currently released CLI'
  type: boolean
  default: true

pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: run
  strategy:
    matrix:
      'linters':
        python: '3.12'
        toxEnvStr: 'lint'
        desc: 'Flake8, Pylint'
      ${{ if parameters.python39 }}:
        ${{ if parameters.azmin }}:
          'python 3.9 tests, min CLI':
            python: '3.9'
            toxEnvStr: 'py3.9-azmin-unit'
            desc: 'python 3.9 tests, min CLI'
        ${{ if parameters.azcur }}:
          'python 3.9 tests, current CLI':
            python: '3.9'
            toxEnvStr: 'py3.9-azcur-unit'
            desc: 'Python 3.9 tests, current CLI'
        ${{ if parameters.azdev }}:
          'python 3.9 tests, dev CLI':
            python: '3.9'
            toxEnvStr: 'py3.9-azdev-unit'
            desc: 'Python 3.9 tests, dev CLI'
      ${{ if parameters.python310 }}:
        ${{ if parameters.azmin }}:
          'python 3.10 tests, min CLI':
            python: '3.10'
            toxEnvStr: 'py3.10-azmin-unit'
            desc: 'Python 3.10 tests, min CLI'
        ${{ if parameters.azcur }}:
          'python 3.10 tests, current CLI':
            python: '3.10'
            toxEnvStr: 'py3.10-azcur-unit'
            desc: 'Python 3.10 tests, current CLI'
        ${{ if parameters.azdev }}:
          'python 3.10 tests, dev CLI':
            python: '3.10'
            toxEnvStr: 'py3.10-azdev-unit'
            desc: 'Python 3.10 tests, dev CLI'
      ${{ if parameters.python311 }}:
        ${{ if parameters.azcur }}:
          'python 3.11 tests, current CLI':
            python: '3.11'
            toxEnvStr: 'py3.11-azcur-unit'
            desc: 'Python 3.11 tests, current CLI'
        ${{ if parameters.azdev }}:
          'python 3.11 tests, dev CLI':
            python: '3.11'
            toxEnvStr: 'py3.11-azdev-unit'
            desc: 'Python 3.11 tests, dev CLI'
      ${{ if parameters.python312 }}:
        ${{ if parameters.azcur }}:
          'python 3.12 tests, current CLI':
            python: '3.12'
            toxEnvStr: 'py3.12-azcur-unit'
            desc: 'Python 3.12 tests, current CLI'
        ${{ if parameters.azdev }}:
          'python 3.12 tests, dev CLI':
            python: '3.12'
            toxEnvStr: 'py3.12-azdev-unit'
            desc: 'Python 3.12 tests, dev CLI'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python)
      architecture: 'x64'
    displayName: 'Use Python $(python) for tests.'
  - template: templates/clone-cli-repo.yml
  - template: templates/setup-tox.yml
  - template: templates/set-testenv-sentinel.yml
  - script: python -m tox -e "$(toxEnvStr)" -vv
    displayName: $(desc)
    env:
        AZEXT_IOT_TESTRG: "test"