# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DigitalTwinInterfacesPatchInterfacesValue(Model):
    """DigitalTwinInterfacesPatchInterfacesValue.

    :param properties: List of properties to update in an interface.
    :type properties: dict[str,
     ~service.models.DigitalTwinInterfacesPatchInterfacesValuePropertiesValue]
    """

    _attribute_map = {
        'properties': {'key': 'properties', 'type': '{DigitalTwinInterfacesPatchInterfacesValuePropertiesValue}'},
    }

    def __init__(self, *, properties=None, **kwargs) -> None:
        super(DigitalTwinInterfacesPatchInterfacesValue, self).__init__(**kwargs)
        self.properties = properties
