# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Property(Model):
    """Property.

    :param reported:
    :type reported: ~service.models.Reported
    :param desired:
    :type desired: ~service.models.Desired
    """

    _attribute_map = {
        'reported': {'key': 'reported', 'type': 'Reported'},
        'desired': {'key': 'desired', 'type': 'Desired'},
    }

    def __init__(self, *, reported=None, desired=None, **kwargs) -> None:
        super(Property, self).__init__(**kwargs)
        self.reported = reported
        self.desired = desired
