# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegenerateDeviceKey(Model):
    """RegenerateDeviceKey.

    :param id: The unique identifier of the device.
    :type id: str
    :param module_id: The unique identifier of the module.
    :type module_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'module_id': {'key': 'moduleId', 'type': 'str'},
    }

    def __init__(self, *, id: str=None, module_id: str=None, **kwargs) -> None:
        super(RegenerateDeviceKey, self).__init__(**kwargs)
        self.id = id
        self.module_id = module_id
