# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EventRoutesListOptions(Model):
    """Additional parameters for list operation.

    :param traceparent: Identifies the request in a distributed tracing
     system.
    :type traceparent: str
    :param tracestate: Provides vendor-specific trace identification
     information and is a companion to traceparent.
    :type tracestate: str
    :param max_items_per_page: The maximum number of items to retrieve per
     request. The server may choose to return less than the requested number.
    :type max_items_per_page: int
    """

    _attribute_map = {
        'traceparent': {'key': '', 'type': 'str'},
        'tracestate': {'key': '', 'type': 'str'},
        'max_items_per_page': {'key': '', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(EventRoutesListOptions, self).__init__(**kwargs)
        self.traceparent = kwargs.get('traceparent', None)
        self.tracestate = kwargs.get('tracestate', None)
        self.max_items_per_page = kwargs.get('max_items_per_page', None)
