# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._operations import ApiTokensOperations
from ._operations import DeviceGroupsOperations
from ._operations import DeviceTemplatesOperations
from ._operations import DevicesOperations
from ._operations import FileUploadsOperations
from ._operations import OrganizationsOperations
from ._operations import RolesOperations
from ._operations import UsersOperations

from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "ApiTokensOperations",
    "DeviceGroupsOperations",
    "DeviceTemplatesOperations",
    "DevicesOperations",
    "FileUploadsOperations",
    "OrganizationsOperations",
    "RolesOperations",
    "UsersOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
