name: "[auto] CLI Command Table Linter"
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false

jobs:
  linter:
    permissions:
      contents: read
    continue-on-error: ${{ inputs.continue-on-error }}
    name: Evaluate command table
    runs-on: ubuntu-latest
    steps:
    # checkout source (for linter_exclusions)
    - uses: actions/checkout@v4

    # download built wheel (from ./release_build.yml)
    - name: Download Wheel
      uses: actions/download-artifact@v4
      with:
        name: azure-iot-cli-ext
        path: ./extension

    # Install python
    - uses: actions/setup-python@v5
      name: Setup python
      with:
          python-version: "3.12"

    # Lint
    - name: azdev linter
      run: |
        set -ev
        pip install virtualenv
        python -m virtualenv venv/
        source ./venv/bin/activate
        pip install -r dev_requirements
        git clone --single-branch -b dev https://github.com/Azure/azure-cli.git ../azure-cli
        pip install azdev
        azdev --version
        azdev setup -c ../azure-cli -r ./
        AZURE_EXTENSION_DIR=~/.azure/cliextensions
        ARTIFACTS_DIR=./extension
        WHEELS=$(ls $ARTIFACTS_DIR/*.whl)
        az --version
        for i in $WHEELS; do
          az extension add --source $i -y --debug
        done
        cp ./linter_exclusions.yml $AZURE_EXTENSION_DIR/azure-iot/
        # temp fix for newest azdev v0.1.65
        cp .pylintrc pylintrc
        azdev linter --include-whl-extensions azure-iot --min-severity medium