name: "[auto] CLI Command Table Linter"
permissions: {}
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false

jobs:
  linter:
    permissions:
      contents: read
    continue-on-error: ${{ inputs.continue-on-error }}
    name: Evaluate command table
    runs-on: ubuntu-latest
    steps:
      # checkout source (for linter_exclusions)
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      # download built wheel (from ./release_build.yml)
      - name: Download Wheel
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: azure-iot-cli-ext
          path: ./extension

      # Install python
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        name: Setup python
        with:
          python-version: "3.13"

      # Lint
      - name: azdev linter
        run: |
          set -ev
          pip install virtualenv
          python -m virtualenv venv/
          source ./venv/bin/activate
          pip install -r dev_requirements
          git clone --single-branch -b dev https://github.com/Azure/azure-cli.git ../azure-cli
          pip install azdev
          azdev --version
          azdev setup -c ../azure-cli -r ./
          AZURE_EXTENSION_DIR=~/.azure/cliextensions
          ARTIFACTS_DIR=./extension
          WHEELS=$(ls $ARTIFACTS_DIR/*.whl)
          az --version
          for i in $WHEELS; do
            az extension add --source $i -y --debug
          done
          cp ./linter_exclusions.yml $AZURE_EXTENSION_DIR/azure-iot/
          # temp fix for newest azdev v0.1.65
          cp .pylintrc pylintrc
          azdev linter --include-whl-extensions azure-iot --min-severity medium
