name: CI Build and Test
run-name: "CI Build and Test"
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - dev
      - preview
      - 1.1.0-preview
      - "release/**"
    tags:
      - "**"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/ci_build.yml
  test:
    uses: ./.github/workflows/tox.yml
    with:
      pr-matrix: ${{ github.event_name == 'pull_request' }}
  linter:
    needs: [build]
    uses: ./.github/workflows/azdev_linter.yml
