name: CI Build and Test
permissions:
  contents: read
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/ci_build.yml
  test:
    uses: ./.github/workflows/tox.yml
  linter:
    needs: [build]
    uses: ./.github/workflows/azdev_linter.yml