name: Testing dynamic matrix
on:
  workflow_dispatch:
    inputs:
      python:
        description: 'Python versions'
        required: true
        default: '["3.11", "3.10", "3.9", "3.8"]'
      toxenv:
        description: 'Tox envs to run'
        required: true
        default: '["Central", "ADT", "DPS", "Hub1", "Hub2", "ADU"]'
      

permissions:
  contents: read
  id-token: write

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
        python: ${{ inputs.python}}
        toxenv: ${{ inputs.toxenv}}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
            echo "python" $python
            echo "toxenv" $toxenv
            
            matrix="{\"py\": $python, \"toxenv\": $toxenv}"
            echo "matrix" $matrix

            echo "matrix=$matrix" >> $GITHUB_OUTPUT
  int-test:
    name: toxenv ${{ matrix.toxenv }} - python ${{ matrix.py }}
    needs: [test-matrix]
    continue-on-error: ${{ inputs.continue-on-error }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.test-matrix.outputs.matrix)}}
    runs-on: ubuntu-22.04
    steps:
      - name: test
        run: |
            echo "Running test"
            echo "py: ${{ matrix.py }}"
            echo "toxenv: ${{ matrix.toxenv }}"