name: "[auto] Security Checks"
on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - dev
      - feature/*
      - release/*
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false
permissions: {}
jobs:
  sdl:
    continue-on-error: ${{ inputs.continue-on-error || false }}
    name: SDL Compliance Checks
    runs-on: windows-latest
    permissions:
      # needed to write security info to repository
      id-token: write
      security-events: write
      contents: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Install dotnet, used by MSDO
    - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: |
          5.0.x
          6.0.x

      # Run analyzers
    - name: Run Microsoft Security DevOps Analysis
      uses: microsoft/security-devops-action@5b26a185ff02cf7c100778adeff0ebbf704ca144 # v1
      id: msdo
      env:
        # file path to analyze
        GDN_BANDIT_TARGET: 'azext_iot'
        GDN_BANDIT_RECURSIVE: true

      # Upload alerts to the Security tab
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact
    - name: Upload alerts artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:  
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
