name: "[auto] Security Checks"
on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - dev
      - feature/*
      - release/*
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false
permissions: {}
jobs:
  sdl:
    continue-on-error: ${{ inputs.continue-on-error || false }}
    name: SDL Compliance Checks
    runs-on: windows-latest
    permissions:
      # needed to write security info to repository
      id-token: write
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

        # Install dotnet, used by MSDO
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: |
            5.0.x
            6.0.x

        # Run analyzers
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@08976cb623803b1b36d7112d4ff9f59eae704de0 # v1.12.0
        id: msdo
        env:
          # file path to analyze
          GDN_BANDIT_TARGET: "azext_iot"
          GDN_BANDIT_RECURSIVE: true

        # Upload alerts to the Security tab
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

        # Upload alerts file as a workflow artifact
      - name: Upload alerts artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: alerts
          path: ${{ steps.msdo.outputs.sarifFile }}
