name: Tox integration tests
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  int-test:
    name: Int test ${{ matrix.toxenv }} - python ${{ matrix.py }}
    continue-on-error: ${{ inputs.continue-on-error }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
        #   - "3.9"
        #   - "3.8"
        toxenv:
        #   - "Central"
        #   - "ADT"
          - "DPS"
        #   - "Hub1"
          - "Hub2"
        #   - "ADU"
    runs-on: ubuntu-22.04
    env:
        AZEXT_IOT_TESTRG: ${{ secrets.AZEXT_IOT_TESTRG}}
        AZEXT_IOT_TESTSTORAGEACCOUNT: ${{ secrets.AZEXT_IOT_TESTSTORAGEACCOUNT}}
        AZEXT_DT_ADX_CLUSTER: ${{ secrets.AZEXT_DT_ADX_CLUSTER}}
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
      - name: Setup test suite
        run: tox r -vv --notest
      - name: "AZ CLI login"
        uses: azure/login@v2
        with:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_SUBCRIPTION_ID: ${{ secrets.AZURE_SUBCRIPTION_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      - name: Run test suite
        run: tox r --skip-pkg-install -e ${{ matrix.toxenv }}-int