name: Tox tests
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  unit-test:
    name: Unit test ${{ matrix.py }} - ${{ matrix.os }}
    continue-on-error: ${{ inputs.continue-on-error }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        py:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
  code-coverage:
    name: Calculate code coverage
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run code coverage
        run: |
          python -m pip install tox
          tox -e coverage
          coverage=$(jq .totals.percent_covered coverage.json | cut -c1-4)
          echo "Code coverage: $coverage%" >> $GITHUB_STEP_SUMMARY
      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          path: ./htmlcov
          name: code_coverage
