name: Run Azure DevOps Integration Tests
on:
  workflow_call:
    inputs:
      showLogs:
        description: "Show logs"
        required: false
        type: boolean
        default: false
      testCentral:
        description: Run Central tests
        type: boolean
        default: true
      testADT:
        description: Run ADT tests
        type: boolean
        default: true
      testDPS:
        description: Run DPS tests
        type: boolean
        default: true
      testHub:
        description: Run Hub tests
        type: boolean
        default: true
      testADU:
        description: Run ADU tests
        type: boolean
        default: true
    # These tests currently time out with federated credentials and must be tested locally
      testADUupdate:
        description: Run ADU update tests
        type: boolean
        default: false
      python_versions:
        description: "Python versions to test"
        required: true
        type: string
        default: >
          {
              Python38: { python: '3.8' },
              Python39: { python: '3.9' },
              Python310: { python: '3.10' }
          }
    secrets:
      ADO_PAT:
        required: true
  workflow_dispatch:
    inputs:
      showLogs:
        description: "Show logs"
        required: false
        type: boolean
        default: false
      testCentral:
        description: Run Central tests
        type: boolean
        default: true
      testADT:
        description: Run ADT tests
        type: boolean
        default: true
      testDPS:
        description: Run DPS tests
        type: boolean
        default: true
      testHub:
        description: Run Hub tests
        type: boolean
        default: true
      testADU:
        description: Run ADU tests
        type: boolean
        default: true
    # These tests currently time out with federated credentials and must be tested locally
      testADUupdate:
        description: Run ADU update tests
        type: boolean
        default: false
      python_versions:
        description: "Python versions to test"
        required: true
        type: string
        default: >
            "{
                Python38: { python: '3.8' },
                Python39: { python: '3.9' },
                Python310: { python: '3.10' }
            }"
env:
  DEFAULT_TITLE: "Azure DevOps Pipeline"
  AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
  DEFINITION_ID: 147
  ORG: azureiotdevxp
  PROJECT: aziotcli
jobs:
  call-ado-pipeline:
    runs-on: ubuntu-latest
    name: Run integration tests
    outputs:
      runId: ${{ steps.start.outputs.runId }}
      portalUrl: ${{ steps.start.outputs.portalUrl }}
      url: ${{ steps.start.outputs.url }}
    steps:
      - shell: bash
        id: start
        name: Trigger the pipeline
        run: |-
          set -ex
          if [ -z "$ORG" ]; then
            echo "::error::Organization is required"
            exit 1
          fi
          if [ -z "$PROJECT" ]; then
            echo "::error::Project is required"
            exit 1
          fi

          cmdArgs=(--org "https://dev.azure.com/$ORG" --project "$PROJECT" --branch "ado_tests")

          if [ -n "$DEFINITION_ID" ]; then
            cmdArgs+=(--id "$DEFINITION_ID")
          else
            echo "::error::Pipeline definition ID must be provided"
            exit 1
          fi

          cmdArgs+=("--parameters")
          cmdArgs+=("pythonVersionsTestingMatrix=\"${{inputs.python_versions}}\")
          cmdArgs+=("testCentral=${{inputs.testCentral}}")
          cmdArgs+=("testADT=${{inputs.testADT}}")
          cmdArgs+=("testDPS=${{inputs.testDPS}}")
          cmdArgs+=("testHub=${{inputs.testHub}}")
          cmdArgs+=("testADU=${{inputs.testADU}}")
          cmdArgs+=("testADUupdate=${{inputs.testADUupdate}}")
          echo "Running: az pipelines run ${cmdArgs[@]}"
          res=$(az pipelines run "${cmdArgs[@]}")

          if [ -z "$res" ]; then
            echo "::error::Failed to trigger the pipeline"
          fi
          runId=$(echo $res | jq -r '.id')
          portalUrl="https://dev.azure.com/$ORG/$PROJECT/_build/results?buildId=$runId&view=results"
          url=$(echo $res | jq -r '.url')
          echo "runId=$runId" >> $GITHUB_OUTPUT
          echo "portalUrl=$portalUrl" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT
      - name: Summary
        id: summary
        run: |-
          echo "# ${PIPELINE:-$DEFAULT_TITLE} Started" >> $GITHUB_STEP_SUMMARY
          echo "## Azure DevOps Pipeline" >> $GITHUB_STEP_SUMMARY
          echo "You can follow the progress [here](${{ steps.start.outputs.portalUrl }})" >> $GITHUB_STEP_SUMMARY

  wait-for-completion:
    runs-on: ubuntu-latest
    name: Wait for the pipeline to complete
    needs: [call-ado-pipeline]
    env:
      SHOW_LOGS: ${{ inputs.showLogs }}
      RUN_ID: ${{ needs.call-ado-pipeline.outputs.runId }}
      PORTAL_URL: ${{ needs.call-ado-pipeline.outputs.portalUrl }}
    steps:
      - name: Wait for the pipeline to complete
        run: |
          set -e
          runId="${{ needs.call-ado-pipeline.outputs.runId }}"
          status="none"
          result="none"
          lastLog=1
          while [[ "$status" =~ (inProgress|notStarted|postponed|none) ]]; do
            sleep 60
            res=$(az pipelines runs show --id "$RUN_ID" --org "https://dev.azure.com/$ORG" --project "$PROJECT")
            status=$(echo "$res" | jq -r '.status')
            result=$(echo "$res" | jq -r '.result')
            logsUrl=$(echo "$res" | jq -r '.logs.url')
            logsList=$(curl -s -u ":$AZURE_DEVOPS_EXT_PAT" -H "Content-Type: application/json" -X GET "$logsUrl")
            count=$(echo $logsList | jq -r '.count')

            if [[ "$SHOW_LOGS" == "false" ]]; then
              continue
            fi

            # we skip the first log as it's the pipeline template
            # also we want to log up to n-1 logs because the current log is still being written to

            items=$(echo $logsList | jq -r '.value')
            if [[ $count -gt 1 ]]; then
              for i in $(seq $(($lastLog+1)) $(($count-1))); do
                log="${logsUrl}/$i" # or we can use jq to get the log url from each item
                curl -s -u ":$AZURE_DEVOPS_EXT_PAT" -H "Content-Type: application/json" -X GET "$log" 
                lastLog=$i
                echo "===================================================================================================="
                echo "Logs are streaming in. For more realtime structured logs, check ${PORTAL_URL}"
                echo "===================================================================================================="
                sleep 2
              done
            fi
          done

          # if status is not completed, or the result is one of failed, canceled; then fail the job
          if [[ "$status" != "completed" || "$result" =~ (failed|canceled) ]]; then
            echo "::error::Pipeline did not complete successfully"
            echo "# ❌ ${PIPELINE:-$DEFAULT_TITLE} Failed ❌" >> $GITHUB_STEP_SUMMARY
            echo "The pipeline did not complete successfully. Please check the logs [here](${PORTAL_URL})" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          if [[ "$SHOW_LOGS" == "true" ]]; then
            # curl the last log
            curl -s -u ":$AZURE_DEVOPS_EXT_PAT" -H "Content-Type: application/json" -X GET "${logsUrl}/${count}"
          fi

          echo "# ✅ ${PIPELINE:-$DEFAULT_TITLE} Completed ✅" >> $GITHUB_STEP_SUMMARY
          echo "The pipeline completed successfully. You can check the logs [here](${PORTAL_URL})" >> $GITHUB_STEP_SUMMARY
  CancelPipeline:
    runs-on: ubuntu-latest
    needs: [call-ado-pipeline, wait-for-completion]
    if: cancelled()
    env:
      RUN_ID: ${{ needs.call-ado-pipeline.outputs.runId }}
      RUN_URL: ${{ needs.call-ado-pipeline.outputs.url }}
      PORTAL_URL: ${{ needs.call-ado-pipeline.outputs.portalUrl }}
    steps:
      - name: Cancel the pipeline
        run: |
          set -ex
          if [[ -z "$RUN_ID" ]]; then
            echo "No pipeline to cancel"
            exit 0
          fi

          curl \
            -X PATCH \
            -u ":$AZURE_DEVOPS_EXT_PAT" \
            -H "Content-Type: application/json" \
            -d '{"status": "cancelling"}' \
            "${RUN_URL}?api-version=7.2-preview.7"
          echo "# ❌ ${PIPELINE:-$DEFAULT_TITLE} Cancelled ❌" >> $GITHUB_STEP_SUMMARY
          echo "The pipeline was cancelled. You can check the logs [here](${PORTAL_URL})" >> $GITHUB_STEP_SUMMARY
